// Code generated by protoc-gen-go. DO NOT EDIT.
// source: project.proto

package projectproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Project struct {
	// @inject_tag: bson:"_id"
	Id                    string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	Title                 string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Student               string   `protobuf:"bytes,3,opt,name=student,proto3" json:"student,omitempty"`
	PrincipalInvestigator string   `protobuf:"bytes,4,opt,name=principalInvestigator,proto3" json:"principalInvestigator,omitempty"`
	CoInvestigators       []string `protobuf:"bytes,5,rep,name=coInvestigators,proto3" json:"coInvestigators,omitempty"`
	Sec                   string   `protobuf:"bytes,6,opt,name=sec,proto3" json:"sec,omitempty"`
	Dor                   string   `protobuf:"bytes,7,opt,name=dor,proto3" json:"dor,omitempty"`
	Dots                  string   `protobuf:"bytes,8,opt,name=dots,proto3" json:"dots,omitempty"`
	Dotc                  string   `protobuf:"bytes,9,opt,name=dotc,proto3" json:"dotc,omitempty"`
	CreatedAt             string   `protobuf:"bytes,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	ThesisPortalID        string   `protobuf:"bytes,11,opt,name=thesisPortalID,proto3" json:"thesisPortalID,omitempty"`
	PrPortalID            string   `protobuf:"bytes,12,opt,name=prPortalID,proto3" json:"prPortalID,omitempty"`
	Progress              int32    `protobuf:"varint,13,opt,name=progress,proto3" json:"progress,omitempty"`
	PiChatID              string   `protobuf:"bytes,14,opt,name=piChatID,proto3" json:"piChatID,omitempty"`
	SecChatID             string   `protobuf:"bytes,15,opt,name=secChatID,proto3" json:"secChatID,omitempty"`
	DorChatID             string   `protobuf:"bytes,16,opt,name=dorChatID,proto3" json:"dorChatID,omitempty"`
	IrbMeetingID          string   `protobuf:"bytes,17,opt,name=irbMeetingID,proto3" json:"irbMeetingID,omitempty"`
	Doa                   string   `protobuf:"bytes,18,opt,name=doa,proto3" json:"doa,omitempty"`
	Period                string   `protobuf:"bytes,19,opt,name=period,proto3" json:"period,omitempty"`
	IsCompleted           bool     `protobuf:"varint,20,opt,name=isCompleted,proto3" json:"isCompleted,omitempty"`
	Documents             []string `protobuf:"bytes,21,rep,name=documents,proto3" json:"documents,omitempty"`
	IsIhesisDone          bool     `protobuf:"varint,22,opt,name=isIhesisDone,proto3" json:"isIhesisDone,omitempty"`
	IsIRBMeetingDone      bool     `protobuf:"varint,23,opt,name=isIRBMeetingDone,proto3" json:"isIRBMeetingDone,omitempty"`
	IsApproved            bool     `protobuf:"varint,24,opt,name=isApproved,proto3" json:"isApproved,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_a6f01cd21767c61e, []int{0}
}
func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (dst *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(dst, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Project) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Project) GetStudent() string {
	if m != nil {
		return m.Student
	}
	return ""
}

func (m *Project) GetPrincipalInvestigator() string {
	if m != nil {
		return m.PrincipalInvestigator
	}
	return ""
}

func (m *Project) GetCoInvestigators() []string {
	if m != nil {
		return m.CoInvestigators
	}
	return nil
}

func (m *Project) GetSec() string {
	if m != nil {
		return m.Sec
	}
	return ""
}

func (m *Project) GetDor() string {
	if m != nil {
		return m.Dor
	}
	return ""
}

func (m *Project) GetDots() string {
	if m != nil {
		return m.Dots
	}
	return ""
}

func (m *Project) GetDotc() string {
	if m != nil {
		return m.Dotc
	}
	return ""
}

func (m *Project) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Project) GetThesisPortalID() string {
	if m != nil {
		return m.ThesisPortalID
	}
	return ""
}

func (m *Project) GetPrPortalID() string {
	if m != nil {
		return m.PrPortalID
	}
	return ""
}

func (m *Project) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *Project) GetPiChatID() string {
	if m != nil {
		return m.PiChatID
	}
	return ""
}

func (m *Project) GetSecChatID() string {
	if m != nil {
		return m.SecChatID
	}
	return ""
}

func (m *Project) GetDorChatID() string {
	if m != nil {
		return m.DorChatID
	}
	return ""
}

func (m *Project) GetIrbMeetingID() string {
	if m != nil {
		return m.IrbMeetingID
	}
	return ""
}

func (m *Project) GetDoa() string {
	if m != nil {
		return m.Doa
	}
	return ""
}

func (m *Project) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

func (m *Project) GetIsCompleted() bool {
	if m != nil {
		return m.IsCompleted
	}
	return false
}

func (m *Project) GetDocuments() []string {
	if m != nil {
		return m.Documents
	}
	return nil
}

func (m *Project) GetIsIhesisDone() bool {
	if m != nil {
		return m.IsIhesisDone
	}
	return false
}

func (m *Project) GetIsIRBMeetingDone() bool {
	if m != nil {
		return m.IsIRBMeetingDone
	}
	return false
}

func (m *Project) GetIsApproved() bool {
	if m != nil {
		return m.IsApproved
	}
	return false
}

type CreateRequest struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_a6f01cd21767c61e, []int{1}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(dst, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type CreateResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_a6f01cd21767c61e, []int{2}
}
func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (dst *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(dst, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_a6f01cd21767c61e, []int{3}
}
func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (dst *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(dst, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadResponse struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_a6f01cd21767c61e, []int{4}
}
func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (dst *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(dst, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type AddDocumentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Doc                  string   `protobuf:"bytes,2,opt,name=doc,proto3" json:"doc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddDocumentRequest) Reset()         { *m = AddDocumentRequest{} }
func (m *AddDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*AddDocumentRequest) ProtoMessage()    {}
func (*AddDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_a6f01cd21767c61e, []int{5}
}
func (m *AddDocumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDocumentRequest.Unmarshal(m, b)
}
func (m *AddDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDocumentRequest.Marshal(b, m, deterministic)
}
func (dst *AddDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDocumentRequest.Merge(dst, src)
}
func (m *AddDocumentRequest) XXX_Size() int {
	return xxx_messageInfo_AddDocumentRequest.Size(m)
}
func (m *AddDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddDocumentRequest proto.InternalMessageInfo

func (m *AddDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddDocumentRequest) GetDoc() string {
	if m != nil {
		return m.Doc
	}
	return ""
}

type AddDocumentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddDocumentResponse) Reset()         { *m = AddDocumentResponse{} }
func (m *AddDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*AddDocumentResponse) ProtoMessage()    {}
func (*AddDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_a6f01cd21767c61e, []int{6}
}
func (m *AddDocumentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDocumentResponse.Unmarshal(m, b)
}
func (m *AddDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDocumentResponse.Marshal(b, m, deterministic)
}
func (dst *AddDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDocumentResponse.Merge(dst, src)
}
func (m *AddDocumentResponse) XXX_Size() int {
	return xxx_messageInfo_AddDocumentResponse.Size(m)
}
func (m *AddDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddDocumentResponse proto.InternalMessageInfo

type RemoveDocumentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Doc                  string   `protobuf:"bytes,2,opt,name=doc,proto3" json:"doc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveDocumentRequest) Reset()         { *m = RemoveDocumentRequest{} }
func (m *RemoveDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveDocumentRequest) ProtoMessage()    {}
func (*RemoveDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_a6f01cd21767c61e, []int{7}
}
func (m *RemoveDocumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveDocumentRequest.Unmarshal(m, b)
}
func (m *RemoveDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveDocumentRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveDocumentRequest.Merge(dst, src)
}
func (m *RemoveDocumentRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveDocumentRequest.Size(m)
}
func (m *RemoveDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveDocumentRequest proto.InternalMessageInfo

func (m *RemoveDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RemoveDocumentRequest) GetDoc() string {
	if m != nil {
		return m.Doc
	}
	return ""
}

type RemoveDocumentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveDocumentResponse) Reset()         { *m = RemoveDocumentResponse{} }
func (m *RemoveDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveDocumentResponse) ProtoMessage()    {}
func (*RemoveDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_a6f01cd21767c61e, []int{8}
}
func (m *RemoveDocumentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveDocumentResponse.Unmarshal(m, b)
}
func (m *RemoveDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveDocumentResponse.Marshal(b, m, deterministic)
}
func (dst *RemoveDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveDocumentResponse.Merge(dst, src)
}
func (m *RemoveDocumentResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveDocumentResponse.Size(m)
}
func (m *RemoveDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveDocumentResponse proto.InternalMessageInfo

type GetAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllRequest) Reset()         { *m = GetAllRequest{} }
func (m *GetAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllRequest) ProtoMessage()    {}
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_a6f01cd21767c61e, []int{9}
}
func (m *GetAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRequest.Unmarshal(m, b)
}
func (m *GetAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRequest.Marshal(b, m, deterministic)
}
func (dst *GetAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRequest.Merge(dst, src)
}
func (m *GetAllRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllRequest.Size(m)
}
func (m *GetAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRequest proto.InternalMessageInfo

type GetAllResponse struct {
	Projects             []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAllResponse) Reset()         { *m = GetAllResponse{} }
func (m *GetAllResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllResponse) ProtoMessage()    {}
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_a6f01cd21767c61e, []int{10}
}
func (m *GetAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllResponse.Unmarshal(m, b)
}
func (m *GetAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllResponse.Marshal(b, m, deterministic)
}
func (dst *GetAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllResponse.Merge(dst, src)
}
func (m *GetAllResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllResponse.Size(m)
}
func (m *GetAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllResponse proto.InternalMessageInfo

func (m *GetAllResponse) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

type GetByStudentRequest struct {
	Student              string   `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByStudentRequest) Reset()         { *m = GetByStudentRequest{} }
func (m *GetByStudentRequest) String() string { return proto.CompactTextString(m) }
func (*GetByStudentRequest) ProtoMessage()    {}
func (*GetByStudentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_a6f01cd21767c61e, []int{11}
}
func (m *GetByStudentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByStudentRequest.Unmarshal(m, b)
}
func (m *GetByStudentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByStudentRequest.Marshal(b, m, deterministic)
}
func (dst *GetByStudentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByStudentRequest.Merge(dst, src)
}
func (m *GetByStudentRequest) XXX_Size() int {
	return xxx_messageInfo_GetByStudentRequest.Size(m)
}
func (m *GetByStudentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByStudentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByStudentRequest proto.InternalMessageInfo

func (m *GetByStudentRequest) GetStudent() string {
	if m != nil {
		return m.Student
	}
	return ""
}

type GetByStudentResponse struct {
	Projects             []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetByStudentResponse) Reset()         { *m = GetByStudentResponse{} }
func (m *GetByStudentResponse) String() string { return proto.CompactTextString(m) }
func (*GetByStudentResponse) ProtoMessage()    {}
func (*GetByStudentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_a6f01cd21767c61e, []int{12}
}
func (m *GetByStudentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByStudentResponse.Unmarshal(m, b)
}
func (m *GetByStudentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByStudentResponse.Marshal(b, m, deterministic)
}
func (dst *GetByStudentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByStudentResponse.Merge(dst, src)
}
func (m *GetByStudentResponse) XXX_Size() int {
	return xxx_messageInfo_GetByStudentResponse.Size(m)
}
func (m *GetByStudentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByStudentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByStudentResponse proto.InternalMessageInfo

func (m *GetByStudentResponse) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

type SetIRBMeetingRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetIRBMeetingRequest) Reset()         { *m = SetIRBMeetingRequest{} }
func (m *SetIRBMeetingRequest) String() string { return proto.CompactTextString(m) }
func (*SetIRBMeetingRequest) ProtoMessage()    {}
func (*SetIRBMeetingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_a6f01cd21767c61e, []int{13}
}
func (m *SetIRBMeetingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetIRBMeetingRequest.Unmarshal(m, b)
}
func (m *SetIRBMeetingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetIRBMeetingRequest.Marshal(b, m, deterministic)
}
func (dst *SetIRBMeetingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetIRBMeetingRequest.Merge(dst, src)
}
func (m *SetIRBMeetingRequest) XXX_Size() int {
	return xxx_messageInfo_SetIRBMeetingRequest.Size(m)
}
func (m *SetIRBMeetingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetIRBMeetingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetIRBMeetingRequest proto.InternalMessageInfo

func (m *SetIRBMeetingRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SetIRBMeetingRequest) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type SetIRBMeetingResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetIRBMeetingResponse) Reset()         { *m = SetIRBMeetingResponse{} }
func (m *SetIRBMeetingResponse) String() string { return proto.CompactTextString(m) }
func (*SetIRBMeetingResponse) ProtoMessage()    {}
func (*SetIRBMeetingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_a6f01cd21767c61e, []int{14}
}
func (m *SetIRBMeetingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetIRBMeetingResponse.Unmarshal(m, b)
}
func (m *SetIRBMeetingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetIRBMeetingResponse.Marshal(b, m, deterministic)
}
func (dst *SetIRBMeetingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetIRBMeetingResponse.Merge(dst, src)
}
func (m *SetIRBMeetingResponse) XXX_Size() int {
	return xxx_messageInfo_SetIRBMeetingResponse.Size(m)
}
func (m *SetIRBMeetingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetIRBMeetingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetIRBMeetingResponse proto.InternalMessageInfo

type SetIsApprovedRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetIsApprovedRequest) Reset()         { *m = SetIsApprovedRequest{} }
func (m *SetIsApprovedRequest) String() string { return proto.CompactTextString(m) }
func (*SetIsApprovedRequest) ProtoMessage()    {}
func (*SetIsApprovedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_a6f01cd21767c61e, []int{15}
}
func (m *SetIsApprovedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetIsApprovedRequest.Unmarshal(m, b)
}
func (m *SetIsApprovedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetIsApprovedRequest.Marshal(b, m, deterministic)
}
func (dst *SetIsApprovedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetIsApprovedRequest.Merge(dst, src)
}
func (m *SetIsApprovedRequest) XXX_Size() int {
	return xxx_messageInfo_SetIsApprovedRequest.Size(m)
}
func (m *SetIsApprovedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetIsApprovedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetIsApprovedRequest proto.InternalMessageInfo

func (m *SetIsApprovedRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SetIsApprovedRequest) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type SetIsApprovedResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetIsApprovedResponse) Reset()         { *m = SetIsApprovedResponse{} }
func (m *SetIsApprovedResponse) String() string { return proto.CompactTextString(m) }
func (*SetIsApprovedResponse) ProtoMessage()    {}
func (*SetIsApprovedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_a6f01cd21767c61e, []int{16}
}
func (m *SetIsApprovedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetIsApprovedResponse.Unmarshal(m, b)
}
func (m *SetIsApprovedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetIsApprovedResponse.Marshal(b, m, deterministic)
}
func (dst *SetIsApprovedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetIsApprovedResponse.Merge(dst, src)
}
func (m *SetIsApprovedResponse) XXX_Size() int {
	return xxx_messageInfo_SetIsApprovedResponse.Size(m)
}
func (m *SetIsApprovedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetIsApprovedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetIsApprovedResponse proto.InternalMessageInfo

type SetThesisDoneRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetThesisDoneRequest) Reset()         { *m = SetThesisDoneRequest{} }
func (m *SetThesisDoneRequest) String() string { return proto.CompactTextString(m) }
func (*SetThesisDoneRequest) ProtoMessage()    {}
func (*SetThesisDoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_a6f01cd21767c61e, []int{17}
}
func (m *SetThesisDoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetThesisDoneRequest.Unmarshal(m, b)
}
func (m *SetThesisDoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetThesisDoneRequest.Marshal(b, m, deterministic)
}
func (dst *SetThesisDoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetThesisDoneRequest.Merge(dst, src)
}
func (m *SetThesisDoneRequest) XXX_Size() int {
	return xxx_messageInfo_SetThesisDoneRequest.Size(m)
}
func (m *SetThesisDoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetThesisDoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetThesisDoneRequest proto.InternalMessageInfo

func (m *SetThesisDoneRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SetThesisDoneRequest) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type SetThesisDoneResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetThesisDoneResponse) Reset()         { *m = SetThesisDoneResponse{} }
func (m *SetThesisDoneResponse) String() string { return proto.CompactTextString(m) }
func (*SetThesisDoneResponse) ProtoMessage()    {}
func (*SetThesisDoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_project_a6f01cd21767c61e, []int{18}
}
func (m *SetThesisDoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetThesisDoneResponse.Unmarshal(m, b)
}
func (m *SetThesisDoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetThesisDoneResponse.Marshal(b, m, deterministic)
}
func (dst *SetThesisDoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetThesisDoneResponse.Merge(dst, src)
}
func (m *SetThesisDoneResponse) XXX_Size() int {
	return xxx_messageInfo_SetThesisDoneResponse.Size(m)
}
func (m *SetThesisDoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetThesisDoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetThesisDoneResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Project)(nil), "projectproto.Project")
	proto.RegisterType((*CreateRequest)(nil), "projectproto.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "projectproto.CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "projectproto.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "projectproto.ReadResponse")
	proto.RegisterType((*AddDocumentRequest)(nil), "projectproto.AddDocumentRequest")
	proto.RegisterType((*AddDocumentResponse)(nil), "projectproto.AddDocumentResponse")
	proto.RegisterType((*RemoveDocumentRequest)(nil), "projectproto.RemoveDocumentRequest")
	proto.RegisterType((*RemoveDocumentResponse)(nil), "projectproto.RemoveDocumentResponse")
	proto.RegisterType((*GetAllRequest)(nil), "projectproto.GetAllRequest")
	proto.RegisterType((*GetAllResponse)(nil), "projectproto.GetAllResponse")
	proto.RegisterType((*GetByStudentRequest)(nil), "projectproto.GetByStudentRequest")
	proto.RegisterType((*GetByStudentResponse)(nil), "projectproto.GetByStudentResponse")
	proto.RegisterType((*SetIRBMeetingRequest)(nil), "projectproto.SetIRBMeetingRequest")
	proto.RegisterType((*SetIRBMeetingResponse)(nil), "projectproto.SetIRBMeetingResponse")
	proto.RegisterType((*SetIsApprovedRequest)(nil), "projectproto.SetIsApprovedRequest")
	proto.RegisterType((*SetIsApprovedResponse)(nil), "projectproto.SetIsApprovedResponse")
	proto.RegisterType((*SetThesisDoneRequest)(nil), "projectproto.SetThesisDoneRequest")
	proto.RegisterType((*SetThesisDoneResponse)(nil), "projectproto.SetThesisDoneResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProjectServiceClient is the client API for ProjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProjectServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	AddDocument(ctx context.Context, in *AddDocumentRequest, opts ...grpc.CallOption) (*AddDocumentResponse, error)
	RemoveDocument(ctx context.Context, in *RemoveDocumentRequest, opts ...grpc.CallOption) (*RemoveDocumentResponse, error)
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error)
	GetByStudent(ctx context.Context, in *GetByStudentRequest, opts ...grpc.CallOption) (*GetByStudentResponse, error)
	SetThesisDone(ctx context.Context, in *SetThesisDoneRequest, opts ...grpc.CallOption) (*SetThesisDoneResponse, error)
	SetIRBMeeting(ctx context.Context, in *SetIRBMeetingRequest, opts ...grpc.CallOption) (*SetIRBMeetingResponse, error)
	SetIsApproved(ctx context.Context, in *SetIsApprovedRequest, opts ...grpc.CallOption) (*SetIsApprovedResponse, error)
}

type projectServiceClient struct {
	cc *grpc.ClientConn
}

func NewProjectServiceClient(cc *grpc.ClientConn) ProjectServiceClient {
	return &projectServiceClient{cc}
}

func (c *projectServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/projectproto.ProjectService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, "/projectproto.ProjectService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) AddDocument(ctx context.Context, in *AddDocumentRequest, opts ...grpc.CallOption) (*AddDocumentResponse, error) {
	out := new(AddDocumentResponse)
	err := c.cc.Invoke(ctx, "/projectproto.ProjectService/AddDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) RemoveDocument(ctx context.Context, in *RemoveDocumentRequest, opts ...grpc.CallOption) (*RemoveDocumentResponse, error) {
	out := new(RemoveDocumentResponse)
	err := c.cc.Invoke(ctx, "/projectproto.ProjectService/RemoveDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error) {
	out := new(GetAllResponse)
	err := c.cc.Invoke(ctx, "/projectproto.ProjectService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetByStudent(ctx context.Context, in *GetByStudentRequest, opts ...grpc.CallOption) (*GetByStudentResponse, error) {
	out := new(GetByStudentResponse)
	err := c.cc.Invoke(ctx, "/projectproto.ProjectService/GetByStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) SetThesisDone(ctx context.Context, in *SetThesisDoneRequest, opts ...grpc.CallOption) (*SetThesisDoneResponse, error) {
	out := new(SetThesisDoneResponse)
	err := c.cc.Invoke(ctx, "/projectproto.ProjectService/SetThesisDone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) SetIRBMeeting(ctx context.Context, in *SetIRBMeetingRequest, opts ...grpc.CallOption) (*SetIRBMeetingResponse, error) {
	out := new(SetIRBMeetingResponse)
	err := c.cc.Invoke(ctx, "/projectproto.ProjectService/SetIRBMeeting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) SetIsApproved(ctx context.Context, in *SetIsApprovedRequest, opts ...grpc.CallOption) (*SetIsApprovedResponse, error) {
	out := new(SetIsApprovedResponse)
	err := c.cc.Invoke(ctx, "/projectproto.ProjectService/SetIsApproved", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectServiceServer is the server API for ProjectService service.
type ProjectServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	AddDocument(context.Context, *AddDocumentRequest) (*AddDocumentResponse, error)
	RemoveDocument(context.Context, *RemoveDocumentRequest) (*RemoveDocumentResponse, error)
	GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error)
	GetByStudent(context.Context, *GetByStudentRequest) (*GetByStudentResponse, error)
	SetThesisDone(context.Context, *SetThesisDoneRequest) (*SetThesisDoneResponse, error)
	SetIRBMeeting(context.Context, *SetIRBMeetingRequest) (*SetIRBMeetingResponse, error)
	SetIsApproved(context.Context, *SetIsApprovedRequest) (*SetIsApprovedResponse, error)
}

func RegisterProjectServiceServer(s *grpc.Server, srv ProjectServiceServer) {
	s.RegisterService(&_ProjectService_serviceDesc, srv)
}

func _ProjectService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projectproto.ProjectService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projectproto.ProjectService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_AddDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).AddDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projectproto.ProjectService/AddDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).AddDocument(ctx, req.(*AddDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_RemoveDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).RemoveDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projectproto.ProjectService/RemoveDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).RemoveDocument(ctx, req.(*RemoveDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projectproto.ProjectService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetAll(ctx, req.(*GetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetByStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetByStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projectproto.ProjectService/GetByStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetByStudent(ctx, req.(*GetByStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_SetThesisDone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetThesisDoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).SetThesisDone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projectproto.ProjectService/SetThesisDone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).SetThesisDone(ctx, req.(*SetThesisDoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_SetIRBMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetIRBMeetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).SetIRBMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projectproto.ProjectService/SetIRBMeeting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).SetIRBMeeting(ctx, req.(*SetIRBMeetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_SetIsApproved_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetIsApprovedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).SetIsApproved(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projectproto.ProjectService/SetIsApproved",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).SetIsApproved(ctx, req.(*SetIsApprovedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProjectService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "projectproto.ProjectService",
	HandlerType: (*ProjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ProjectService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _ProjectService_Read_Handler,
		},
		{
			MethodName: "AddDocument",
			Handler:    _ProjectService_AddDocument_Handler,
		},
		{
			MethodName: "RemoveDocument",
			Handler:    _ProjectService_RemoveDocument_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _ProjectService_GetAll_Handler,
		},
		{
			MethodName: "GetByStudent",
			Handler:    _ProjectService_GetByStudent_Handler,
		},
		{
			MethodName: "SetThesisDone",
			Handler:    _ProjectService_SetThesisDone_Handler,
		},
		{
			MethodName: "SetIRBMeeting",
			Handler:    _ProjectService_SetIRBMeeting_Handler,
		},
		{
			MethodName: "SetIsApproved",
			Handler:    _ProjectService_SetIsApproved_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "project.proto",
}

func init() { proto.RegisterFile("project.proto", fileDescriptor_project_a6f01cd21767c61e) }

var fileDescriptor_project_a6f01cd21767c61e = []byte{
	// 779 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdf, 0x4f, 0xdb, 0x30,
	0x10, 0xa6, 0x94, 0xfe, 0xba, 0xb6, 0x81, 0x99, 0xb6, 0x78, 0x19, 0x9b, 0x42, 0x98, 0xa6, 0x6a,
	0x0f, 0xa0, 0xb1, 0x69, 0xd2, 0x5e, 0xc6, 0x4a, 0x8b, 0x50, 0x1f, 0x26, 0xa1, 0x80, 0x34, 0x09,
	0x69, 0x0f, 0x21, 0xb1, 0x20, 0x53, 0xa9, 0x33, 0xdb, 0xad, 0xb4, 0xc7, 0xfd, 0x81, 0xfb, 0x9f,
	0xa6, 0x38, 0xae, 0x1b, 0xa7, 0xa1, 0x12, 0x3c, 0x35, 0xf7, 0xdd, 0x77, 0x9f, 0x2f, 0x97, 0xfb,
	0xac, 0x42, 0x3b, 0x66, 0xf4, 0x17, 0x09, 0xc4, 0x51, 0xcc, 0xa8, 0xa0, 0xa8, 0xa5, 0x42, 0x19,
	0xb9, 0xff, 0x2a, 0x50, 0xbb, 0x4c, 0x01, 0x64, 0xc1, 0x66, 0x14, 0xe2, 0x92, 0x53, 0xea, 0x37,
	0xbc, 0xcd, 0x28, 0x44, 0x1d, 0xa8, 0x88, 0x48, 0x4c, 0x08, 0xde, 0x94, 0x50, 0x1a, 0x20, 0x0c,
	0x35, 0x2e, 0x66, 0x21, 0x99, 0x0a, 0x5c, 0x96, 0xf8, 0x22, 0x44, 0x9f, 0xa0, 0x1b, 0xb3, 0x68,
	0x1a, 0x44, 0xb1, 0x3f, 0x19, 0x4f, 0xe7, 0x84, 0x8b, 0xe8, 0xce, 0x17, 0x94, 0xe1, 0x2d, 0xc9,
	0x2b, 0x4e, 0xa2, 0x3e, 0x6c, 0x07, 0x34, 0x8b, 0x70, 0x5c, 0x71, 0xca, 0xfd, 0x86, 0x97, 0x87,
	0xd1, 0x0e, 0x94, 0x39, 0x09, 0x70, 0x55, 0xaa, 0x25, 0x8f, 0x09, 0x12, 0x52, 0x86, 0x6b, 0x29,
	0x12, 0x52, 0x86, 0x10, 0x6c, 0x85, 0x54, 0x70, 0x5c, 0x97, 0x90, 0x7c, 0x56, 0x58, 0x80, 0x1b,
	0x1a, 0x0b, 0xd0, 0x3e, 0x34, 0x02, 0x46, 0x7c, 0x41, 0xc2, 0x81, 0xc0, 0x20, 0x13, 0x4b, 0x00,
	0xbd, 0x03, 0x4b, 0xdc, 0x13, 0x1e, 0xf1, 0x4b, 0xca, 0x84, 0x3f, 0x19, 0x8f, 0x70, 0x53, 0x52,
	0x72, 0x28, 0x7a, 0x03, 0x10, 0x33, 0xcd, 0x69, 0x49, 0x4e, 0x06, 0x41, 0x36, 0xd4, 0x63, 0x46,
	0xef, 0x18, 0xe1, 0x1c, 0xb7, 0x9d, 0x52, 0xbf, 0xe2, 0xe9, 0x58, 0xe6, 0xa2, 0xe1, 0xbd, 0x2f,
	0xc6, 0x23, 0x6c, 0xc9, 0x4a, 0x1d, 0x27, 0xdd, 0x71, 0x12, 0xa8, 0xe4, 0x76, 0xda, 0x9d, 0x06,
	0x92, 0x6c, 0x48, 0x99, 0xca, 0xee, 0xa4, 0x59, 0x0d, 0x20, 0x17, 0x5a, 0x11, 0xbb, 0xfd, 0x4e,
	0x88, 0x88, 0xa6, 0x77, 0xe3, 0x11, 0x7e, 0x21, 0x09, 0x06, 0x96, 0xce, 0xcd, 0xc7, 0x68, 0x31,
	0x37, 0x1f, 0xf5, 0xa0, 0x1a, 0x13, 0x16, 0xd1, 0x10, 0xef, 0x4a, 0x50, 0x45, 0xc8, 0x81, 0x66,
	0xc4, 0x87, 0xf4, 0x21, 0x9e, 0x10, 0x41, 0x42, 0xdc, 0x71, 0x4a, 0xfd, 0xba, 0x97, 0x85, 0xd2,
	0x6e, 0x82, 0xd9, 0x03, 0x99, 0x0a, 0x8e, 0xbb, 0xf2, 0xcb, 0x2d, 0x01, 0xd9, 0x0d, 0x1f, 0xcb,
	0xa9, 0x8d, 0xe8, 0x94, 0xe0, 0x9e, 0x14, 0x30, 0x30, 0xf4, 0x1e, 0x76, 0x22, 0x3e, 0xf6, 0xce,
	0x54, 0x7f, 0x92, 0xb7, 0x27, 0x79, 0x2b, 0x78, 0x32, 0xf1, 0x88, 0x0f, 0xe2, 0x98, 0xd1, 0x39,
	0x09, 0x31, 0x96, 0xac, 0x0c, 0xe2, 0x7e, 0x83, 0xf6, 0x50, 0x7e, 0x46, 0x8f, 0xfc, 0x9e, 0x11,
	0x2e, 0xd0, 0x31, 0xd4, 0xd4, 0xc2, 0xcb, 0xcd, 0x6e, 0x9e, 0x74, 0x8f, 0xb2, 0x06, 0x38, 0x52,
	0xcb, 0xef, 0x2d, 0x58, 0xae, 0x03, 0xd6, 0x42, 0x81, 0xc7, 0x74, 0xca, 0x49, 0xde, 0x17, 0xee,
	0x6b, 0x68, 0x7a, 0xc4, 0x0f, 0x17, 0x27, 0xe4, 0xd3, 0xa7, 0xd0, 0x4a, 0xd3, 0xaa, 0xfc, 0xc9,
	0x1d, 0x7c, 0x06, 0x34, 0x08, 0xc3, 0x91, 0x9a, 0xe1, 0x23, 0xc7, 0xa4, 0xdf, 0x30, 0x50, 0xde,
	0x4c, 0x1e, 0xdd, 0x2e, 0xec, 0x1a, 0x75, 0xe9, 0xf9, 0xee, 0x17, 0xe8, 0x7a, 0xe4, 0x81, 0xce,
	0xc9, 0xd3, 0x15, 0x31, 0xf4, 0xf2, 0xa5, 0x4a, 0x74, 0x1b, 0xda, 0x17, 0x44, 0x0c, 0x26, 0x13,
	0x25, 0xe6, 0x0e, 0xc1, 0x5a, 0x00, 0xea, 0xbd, 0x3f, 0xc8, 0xe5, 0x4f, 0xde, 0x88, 0xe3, 0x92,
	0x53, 0x7e, 0xfc, 0xc5, 0x35, 0xcd, 0x3d, 0x86, 0xdd, 0x0b, 0x22, 0xce, 0xfe, 0x5c, 0xa5, 0x37,
	0xca, 0xa2, 0xd1, 0xcc, 0x95, 0x53, 0x32, 0xae, 0x1c, 0x77, 0x0c, 0x1d, 0xb3, 0xe0, 0xf9, 0x67,
	0x7f, 0x85, 0xce, 0x15, 0x11, 0xcb, 0x75, 0x7b, 0x6c, 0x4a, 0x3d, 0xa8, 0x72, 0xe1, 0x8b, 0x19,
	0x97, 0x83, 0xaa, 0x7b, 0x2a, 0x72, 0xf7, 0xa0, 0x9b, 0xab, 0x57, 0xa3, 0x52, 0xc2, 0x7a, 0x47,
	0x9f, 0x29, 0x9c, 0xa9, 0x37, 0x84, 0xaf, 0xb5, 0x91, 0x9e, 0x27, 0x9c, 0xad, 0x4f, 0x85, 0x4f,
	0xfe, 0x56, 0xc1, 0x52, 0x03, 0xba, 0x22, 0x6c, 0x1e, 0x05, 0x04, 0x9d, 0x43, 0x35, 0x75, 0x05,
	0x7a, 0x65, 0x0e, 0xd2, 0x70, 0x9b, 0xbd, 0x5f, 0x9c, 0x54, 0x0d, 0x6f, 0xa0, 0x53, 0xd8, 0x4a,
	0xbc, 0x81, 0x5e, 0x9a, 0xbc, 0x8c, 0x9d, 0x6c, 0xbb, 0x28, 0xa5, 0x05, 0xae, 0xa1, 0x99, 0xd9,
	0x71, 0xe4, 0x98, 0xe4, 0x55, 0xdb, 0xd8, 0x07, 0x6b, 0x18, 0x5a, 0xf5, 0x27, 0x58, 0xe6, 0x9e,
	0xa3, 0xc3, 0x7c, 0x17, 0x05, 0x06, 0xb2, 0xdf, 0xae, 0x27, 0x69, 0xf9, 0x73, 0xa8, 0xa6, 0xde,
	0xc8, 0x0f, 0xcf, 0xb0, 0x50, 0x7e, 0x78, 0xa6, 0x9d, 0xdc, 0x0d, 0xf4, 0x03, 0x5a, 0xd9, 0x65,
	0x47, 0x07, 0x2b, 0xfc, 0xbc, 0x73, 0x6c, 0x77, 0x1d, 0x45, 0x0b, 0xdf, 0x40, 0xdb, 0x58, 0x04,
	0x94, 0x2b, 0x2b, 0xda, 0x32, 0xfb, 0x70, 0x2d, 0x27, 0xa7, 0xbd, 0xb4, 0x45, 0x81, 0xf6, 0x8a,
	0xe7, 0x0a, 0xb4, 0x0b, 0x7c, 0xa5, 0xb5, 0xb5, 0x33, 0x8a, 0xb4, 0xf3, 0xb6, 0x2b, 0xd2, 0x5e,
	0xb5, 0xd6, 0xc6, 0x99, 0x75, 0x63, 0xfc, 0x51, 0xba, 0xad, 0xca, 0x9f, 0x8f, 0xff, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x49, 0x59, 0xb6, 0x52, 0x4e, 0x09, 0x00, 0x00,
}
