// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package userproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Student struct {
	// @inject_tag: bson:"_id"
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty" bson:"_id"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,4,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Gender               string   `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	TypeOfStudent        string   `protobuf:"bytes,6,opt,name=typeOfStudent,proto3" json:"typeOfStudent,omitempty"`
	Doj                  string   `protobuf:"bytes,7,opt,name=doj,proto3" json:"doj,omitempty"`
	Created              string   `protobuf:"bytes,8,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{0}
}
func (m *Student) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Student.Unmarshal(m, b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Student.Marshal(b, m, deterministic)
}
func (dst *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(dst, src)
}
func (m *Student) XXX_Size() int {
	return xxx_messageInfo_Student.Size(m)
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Student) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Student) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Student) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Student) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Student) GetTypeOfStudent() string {
	if m != nil {
		return m.TypeOfStudent
	}
	return ""
}

func (m *Student) GetDoj() string {
	if m != nil {
		return m.Doj
	}
	return ""
}

func (m *Student) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

type Secretariat struct {
	// @inject_tag: bson:"_id"
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty" bson:"_id"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Secretariat) Reset()         { *m = Secretariat{} }
func (m *Secretariat) String() string { return proto.CompactTextString(m) }
func (*Secretariat) ProtoMessage()    {}
func (*Secretariat) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{1}
}
func (m *Secretariat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Secretariat.Unmarshal(m, b)
}
func (m *Secretariat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Secretariat.Marshal(b, m, deterministic)
}
func (dst *Secretariat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Secretariat.Merge(dst, src)
}
func (m *Secretariat) XXX_Size() int {
	return xxx_messageInfo_Secretariat.Size(m)
}
func (m *Secretariat) XXX_DiscardUnknown() {
	xxx_messageInfo_Secretariat.DiscardUnknown(m)
}

var xxx_messageInfo_Secretariat proto.InternalMessageInfo

func (m *Secretariat) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Secretariat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type EC struct {
	// @inject_tag: bson:"_id"
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty" bson:"_id"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Qualification        string   `protobuf:"bytes,3,opt,name=qualification,proto3" json:"qualification,omitempty"`
	CurrentOrganization  string   `protobuf:"bytes,4,opt,name=currentOrganization,proto3" json:"currentOrganization,omitempty"`
	Telephone            string   `protobuf:"bytes,5,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Fax                  string   `protobuf:"bytes,6,opt,name=fax,proto3" json:"fax,omitempty"`
	Designation          string   `protobuf:"bytes,7,opt,name=designation,proto3" json:"designation,omitempty"`
	Affiliation          string   `protobuf:"bytes,8,opt,name=affiliation,proto3" json:"affiliation,omitempty"`
	Gender               string   `protobuf:"bytes,9,opt,name=gender,proto3" json:"gender,omitempty"`
	Position             string   `protobuf:"bytes,10,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EC) Reset()         { *m = EC{} }
func (m *EC) String() string { return proto.CompactTextString(m) }
func (*EC) ProtoMessage()    {}
func (*EC) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{2}
}
func (m *EC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EC.Unmarshal(m, b)
}
func (m *EC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EC.Marshal(b, m, deterministic)
}
func (dst *EC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EC.Merge(dst, src)
}
func (m *EC) XXX_Size() int {
	return xxx_messageInfo_EC.Size(m)
}
func (m *EC) XXX_DiscardUnknown() {
	xxx_messageInfo_EC.DiscardUnknown(m)
}

var xxx_messageInfo_EC proto.InternalMessageInfo

func (m *EC) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EC) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EC) GetQualification() string {
	if m != nil {
		return m.Qualification
	}
	return ""
}

func (m *EC) GetCurrentOrganization() string {
	if m != nil {
		return m.CurrentOrganization
	}
	return ""
}

func (m *EC) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *EC) GetFax() string {
	if m != nil {
		return m.Fax
	}
	return ""
}

func (m *EC) GetDesignation() string {
	if m != nil {
		return m.Designation
	}
	return ""
}

func (m *EC) GetAffiliation() string {
	if m != nil {
		return m.Affiliation
	}
	return ""
}

func (m *EC) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *EC) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

type DOR struct {
	// @inject_tag: bson:"_id"
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty" bson:"_id"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DOR) Reset()         { *m = DOR{} }
func (m *DOR) String() string { return proto.CompactTextString(m) }
func (*DOR) ProtoMessage()    {}
func (*DOR) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{3}
}
func (m *DOR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DOR.Unmarshal(m, b)
}
func (m *DOR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DOR.Marshal(b, m, deterministic)
}
func (dst *DOR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DOR.Merge(dst, src)
}
func (m *DOR) XXX_Size() int {
	return xxx_messageInfo_DOR.Size(m)
}
func (m *DOR) XXX_DiscardUnknown() {
	xxx_messageInfo_DOR.DiscardUnknown(m)
}

var xxx_messageInfo_DOR proto.InternalMessageInfo

func (m *DOR) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *DOR) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PI struct {
	// @inject_tag: bson:"_id"
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty" bson:"_id"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,4,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Gender               string   `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Created              string   `protobuf:"bytes,6,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PI) Reset()         { *m = PI{} }
func (m *PI) String() string { return proto.CompactTextString(m) }
func (*PI) ProtoMessage()    {}
func (*PI) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{4}
}
func (m *PI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PI.Unmarshal(m, b)
}
func (m *PI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PI.Marshal(b, m, deterministic)
}
func (dst *PI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PI.Merge(dst, src)
}
func (m *PI) XXX_Size() int {
	return xxx_messageInfo_PI.Size(m)
}
func (m *PI) XXX_DiscardUnknown() {
	xxx_messageInfo_PI.DiscardUnknown(m)
}

var xxx_messageInfo_PI proto.InternalMessageInfo

func (m *PI) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *PI) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PI) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PI) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *PI) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *PI) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

type CoI struct {
	// @inject_tag: bson:"_id"
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty" bson:"_id"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,4,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Gender               string   `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Created              string   `protobuf:"bytes,6,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoI) Reset()         { *m = CoI{} }
func (m *CoI) String() string { return proto.CompactTextString(m) }
func (*CoI) ProtoMessage()    {}
func (*CoI) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{5}
}
func (m *CoI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoI.Unmarshal(m, b)
}
func (m *CoI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoI.Marshal(b, m, deterministic)
}
func (dst *CoI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoI.Merge(dst, src)
}
func (m *CoI) XXX_Size() int {
	return xxx_messageInfo_CoI.Size(m)
}
func (m *CoI) XXX_DiscardUnknown() {
	xxx_messageInfo_CoI.DiscardUnknown(m)
}

var xxx_messageInfo_CoI proto.InternalMessageInfo

func (m *CoI) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CoI) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CoI) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CoI) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *CoI) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *CoI) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

type HR struct {
	// @inject_tag: bson:"_id"
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HR) Reset()         { *m = HR{} }
func (m *HR) String() string { return proto.CompactTextString(m) }
func (*HR) ProtoMessage()    {}
func (*HR) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{6}
}
func (m *HR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HR.Unmarshal(m, b)
}
func (m *HR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HR.Marshal(b, m, deterministic)
}
func (dst *HR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HR.Merge(dst, src)
}
func (m *HR) XXX_Size() int {
	return xxx_messageInfo_HR.Size(m)
}
func (m *HR) XXX_DiscardUnknown() {
	xxx_messageInfo_HR.DiscardUnknown(m)
}

var xxx_messageInfo_HR proto.InternalMessageInfo

func (m *HR) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *HR) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HR) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

// COMMON
type CreateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{7}
}
func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (dst *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(dst, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

type ReadRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{8}
}
func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (dst *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(dst, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{9}
}
func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(dst, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{10}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(dst, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{11}
}
func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(dst, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

// STUDENT
type CreateStudentRequest struct {
	Student              *Student `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStudentRequest) Reset()         { *m = CreateStudentRequest{} }
func (m *CreateStudentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateStudentRequest) ProtoMessage()    {}
func (*CreateStudentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{12}
}
func (m *CreateStudentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStudentRequest.Unmarshal(m, b)
}
func (m *CreateStudentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStudentRequest.Marshal(b, m, deterministic)
}
func (dst *CreateStudentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStudentRequest.Merge(dst, src)
}
func (m *CreateStudentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateStudentRequest.Size(m)
}
func (m *CreateStudentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStudentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStudentRequest proto.InternalMessageInfo

func (m *CreateStudentRequest) GetStudent() *Student {
	if m != nil {
		return m.Student
	}
	return nil
}

type ReadStudentResponse struct {
	Student              *Student `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadStudentResponse) Reset()         { *m = ReadStudentResponse{} }
func (m *ReadStudentResponse) String() string { return proto.CompactTextString(m) }
func (*ReadStudentResponse) ProtoMessage()    {}
func (*ReadStudentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{13}
}
func (m *ReadStudentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadStudentResponse.Unmarshal(m, b)
}
func (m *ReadStudentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadStudentResponse.Marshal(b, m, deterministic)
}
func (dst *ReadStudentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadStudentResponse.Merge(dst, src)
}
func (m *ReadStudentResponse) XXX_Size() int {
	return xxx_messageInfo_ReadStudentResponse.Size(m)
}
func (m *ReadStudentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadStudentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadStudentResponse proto.InternalMessageInfo

func (m *ReadStudentResponse) GetStudent() *Student {
	if m != nil {
		return m.Student
	}
	return nil
}

type UpdateStudentRequest struct {
	Student              *Student `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateStudentRequest) Reset()         { *m = UpdateStudentRequest{} }
func (m *UpdateStudentRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateStudentRequest) ProtoMessage()    {}
func (*UpdateStudentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{14}
}
func (m *UpdateStudentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStudentRequest.Unmarshal(m, b)
}
func (m *UpdateStudentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStudentRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateStudentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStudentRequest.Merge(dst, src)
}
func (m *UpdateStudentRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateStudentRequest.Size(m)
}
func (m *UpdateStudentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStudentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStudentRequest proto.InternalMessageInfo

func (m *UpdateStudentRequest) GetStudent() *Student {
	if m != nil {
		return m.Student
	}
	return nil
}

// EC
type CreateECRequest struct {
	Ec                   *EC      `protobuf:"bytes,1,opt,name=ec,proto3" json:"ec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateECRequest) Reset()         { *m = CreateECRequest{} }
func (m *CreateECRequest) String() string { return proto.CompactTextString(m) }
func (*CreateECRequest) ProtoMessage()    {}
func (*CreateECRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{15}
}
func (m *CreateECRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateECRequest.Unmarshal(m, b)
}
func (m *CreateECRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateECRequest.Marshal(b, m, deterministic)
}
func (dst *CreateECRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateECRequest.Merge(dst, src)
}
func (m *CreateECRequest) XXX_Size() int {
	return xxx_messageInfo_CreateECRequest.Size(m)
}
func (m *CreateECRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateECRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateECRequest proto.InternalMessageInfo

func (m *CreateECRequest) GetEc() *EC {
	if m != nil {
		return m.Ec
	}
	return nil
}

type ReadECResponse struct {
	Ec                   *EC      `protobuf:"bytes,1,opt,name=ec,proto3" json:"ec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadECResponse) Reset()         { *m = ReadECResponse{} }
func (m *ReadECResponse) String() string { return proto.CompactTextString(m) }
func (*ReadECResponse) ProtoMessage()    {}
func (*ReadECResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{16}
}
func (m *ReadECResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadECResponse.Unmarshal(m, b)
}
func (m *ReadECResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadECResponse.Marshal(b, m, deterministic)
}
func (dst *ReadECResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadECResponse.Merge(dst, src)
}
func (m *ReadECResponse) XXX_Size() int {
	return xxx_messageInfo_ReadECResponse.Size(m)
}
func (m *ReadECResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadECResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadECResponse proto.InternalMessageInfo

func (m *ReadECResponse) GetEc() *EC {
	if m != nil {
		return m.Ec
	}
	return nil
}

type UpdateECRequest struct {
	Ec                   *EC      `protobuf:"bytes,1,opt,name=ec,proto3" json:"ec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateECRequest) Reset()         { *m = UpdateECRequest{} }
func (m *UpdateECRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateECRequest) ProtoMessage()    {}
func (*UpdateECRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{17}
}
func (m *UpdateECRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateECRequest.Unmarshal(m, b)
}
func (m *UpdateECRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateECRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateECRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateECRequest.Merge(dst, src)
}
func (m *UpdateECRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateECRequest.Size(m)
}
func (m *UpdateECRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateECRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateECRequest proto.InternalMessageInfo

func (m *UpdateECRequest) GetEc() *EC {
	if m != nil {
		return m.Ec
	}
	return nil
}

// Secretariat
type CreateSecretariatRequest struct {
	Sec                  *Secretariat `protobuf:"bytes,1,opt,name=sec,proto3" json:"sec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateSecretariatRequest) Reset()         { *m = CreateSecretariatRequest{} }
func (m *CreateSecretariatRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSecretariatRequest) ProtoMessage()    {}
func (*CreateSecretariatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{18}
}
func (m *CreateSecretariatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSecretariatRequest.Unmarshal(m, b)
}
func (m *CreateSecretariatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSecretariatRequest.Marshal(b, m, deterministic)
}
func (dst *CreateSecretariatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSecretariatRequest.Merge(dst, src)
}
func (m *CreateSecretariatRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSecretariatRequest.Size(m)
}
func (m *CreateSecretariatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSecretariatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSecretariatRequest proto.InternalMessageInfo

func (m *CreateSecretariatRequest) GetSec() *Secretariat {
	if m != nil {
		return m.Sec
	}
	return nil
}

type ReadSecretariatResponse struct {
	Sec                  *Secretariat `protobuf:"bytes,1,opt,name=sec,proto3" json:"sec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReadSecretariatResponse) Reset()         { *m = ReadSecretariatResponse{} }
func (m *ReadSecretariatResponse) String() string { return proto.CompactTextString(m) }
func (*ReadSecretariatResponse) ProtoMessage()    {}
func (*ReadSecretariatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{19}
}
func (m *ReadSecretariatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadSecretariatResponse.Unmarshal(m, b)
}
func (m *ReadSecretariatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadSecretariatResponse.Marshal(b, m, deterministic)
}
func (dst *ReadSecretariatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadSecretariatResponse.Merge(dst, src)
}
func (m *ReadSecretariatResponse) XXX_Size() int {
	return xxx_messageInfo_ReadSecretariatResponse.Size(m)
}
func (m *ReadSecretariatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadSecretariatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadSecretariatResponse proto.InternalMessageInfo

func (m *ReadSecretariatResponse) GetSec() *Secretariat {
	if m != nil {
		return m.Sec
	}
	return nil
}

type UpdateSecretariatRequest struct {
	Sec                  *Secretariat `protobuf:"bytes,1,opt,name=sec,proto3" json:"sec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateSecretariatRequest) Reset()         { *m = UpdateSecretariatRequest{} }
func (m *UpdateSecretariatRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSecretariatRequest) ProtoMessage()    {}
func (*UpdateSecretariatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{20}
}
func (m *UpdateSecretariatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSecretariatRequest.Unmarshal(m, b)
}
func (m *UpdateSecretariatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSecretariatRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateSecretariatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSecretariatRequest.Merge(dst, src)
}
func (m *UpdateSecretariatRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSecretariatRequest.Size(m)
}
func (m *UpdateSecretariatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSecretariatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSecretariatRequest proto.InternalMessageInfo

func (m *UpdateSecretariatRequest) GetSec() *Secretariat {
	if m != nil {
		return m.Sec
	}
	return nil
}

// PI
type CreatePIRequest struct {
	Pi                   *PI      `protobuf:"bytes,1,opt,name=pi,proto3" json:"pi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePIRequest) Reset()         { *m = CreatePIRequest{} }
func (m *CreatePIRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePIRequest) ProtoMessage()    {}
func (*CreatePIRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{21}
}
func (m *CreatePIRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePIRequest.Unmarshal(m, b)
}
func (m *CreatePIRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePIRequest.Marshal(b, m, deterministic)
}
func (dst *CreatePIRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePIRequest.Merge(dst, src)
}
func (m *CreatePIRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePIRequest.Size(m)
}
func (m *CreatePIRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePIRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePIRequest proto.InternalMessageInfo

func (m *CreatePIRequest) GetPi() *PI {
	if m != nil {
		return m.Pi
	}
	return nil
}

type ReadPIResponse struct {
	Pi                   *PI      `protobuf:"bytes,1,opt,name=pi,proto3" json:"pi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadPIResponse) Reset()         { *m = ReadPIResponse{} }
func (m *ReadPIResponse) String() string { return proto.CompactTextString(m) }
func (*ReadPIResponse) ProtoMessage()    {}
func (*ReadPIResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{22}
}
func (m *ReadPIResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadPIResponse.Unmarshal(m, b)
}
func (m *ReadPIResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadPIResponse.Marshal(b, m, deterministic)
}
func (dst *ReadPIResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadPIResponse.Merge(dst, src)
}
func (m *ReadPIResponse) XXX_Size() int {
	return xxx_messageInfo_ReadPIResponse.Size(m)
}
func (m *ReadPIResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadPIResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadPIResponse proto.InternalMessageInfo

func (m *ReadPIResponse) GetPi() *PI {
	if m != nil {
		return m.Pi
	}
	return nil
}

type UpdatePIRequest struct {
	Pi                   *PI      `protobuf:"bytes,1,opt,name=pi,proto3" json:"pi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePIRequest) Reset()         { *m = UpdatePIRequest{} }
func (m *UpdatePIRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePIRequest) ProtoMessage()    {}
func (*UpdatePIRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{23}
}
func (m *UpdatePIRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePIRequest.Unmarshal(m, b)
}
func (m *UpdatePIRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePIRequest.Marshal(b, m, deterministic)
}
func (dst *UpdatePIRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePIRequest.Merge(dst, src)
}
func (m *UpdatePIRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePIRequest.Size(m)
}
func (m *UpdatePIRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePIRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePIRequest proto.InternalMessageInfo

func (m *UpdatePIRequest) GetPi() *PI {
	if m != nil {
		return m.Pi
	}
	return nil
}

// CoI
type CreateCoIRequest struct {
	Coi                  *EC      `protobuf:"bytes,1,opt,name=coi,proto3" json:"coi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCoIRequest) Reset()         { *m = CreateCoIRequest{} }
func (m *CreateCoIRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCoIRequest) ProtoMessage()    {}
func (*CreateCoIRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{24}
}
func (m *CreateCoIRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCoIRequest.Unmarshal(m, b)
}
func (m *CreateCoIRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCoIRequest.Marshal(b, m, deterministic)
}
func (dst *CreateCoIRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCoIRequest.Merge(dst, src)
}
func (m *CreateCoIRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCoIRequest.Size(m)
}
func (m *CreateCoIRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCoIRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCoIRequest proto.InternalMessageInfo

func (m *CreateCoIRequest) GetCoi() *EC {
	if m != nil {
		return m.Coi
	}
	return nil
}

type ReadCoIResponse struct {
	Coi                  *CoI     `protobuf:"bytes,1,opt,name=coi,proto3" json:"coi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadCoIResponse) Reset()         { *m = ReadCoIResponse{} }
func (m *ReadCoIResponse) String() string { return proto.CompactTextString(m) }
func (*ReadCoIResponse) ProtoMessage()    {}
func (*ReadCoIResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{25}
}
func (m *ReadCoIResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadCoIResponse.Unmarshal(m, b)
}
func (m *ReadCoIResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadCoIResponse.Marshal(b, m, deterministic)
}
func (dst *ReadCoIResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadCoIResponse.Merge(dst, src)
}
func (m *ReadCoIResponse) XXX_Size() int {
	return xxx_messageInfo_ReadCoIResponse.Size(m)
}
func (m *ReadCoIResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadCoIResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadCoIResponse proto.InternalMessageInfo

func (m *ReadCoIResponse) GetCoi() *CoI {
	if m != nil {
		return m.Coi
	}
	return nil
}

type UpdateCoIRequest struct {
	Coi                  *CoI     `protobuf:"bytes,1,opt,name=coi,proto3" json:"coi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCoIRequest) Reset()         { *m = UpdateCoIRequest{} }
func (m *UpdateCoIRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCoIRequest) ProtoMessage()    {}
func (*UpdateCoIRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{26}
}
func (m *UpdateCoIRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCoIRequest.Unmarshal(m, b)
}
func (m *UpdateCoIRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCoIRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateCoIRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCoIRequest.Merge(dst, src)
}
func (m *UpdateCoIRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCoIRequest.Size(m)
}
func (m *UpdateCoIRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCoIRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCoIRequest proto.InternalMessageInfo

func (m *UpdateCoIRequest) GetCoi() *CoI {
	if m != nil {
		return m.Coi
	}
	return nil
}

// DOR
type CreateDORRequest struct {
	Dor                  *DOR     `protobuf:"bytes,1,opt,name=dor,proto3" json:"dor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDORRequest) Reset()         { *m = CreateDORRequest{} }
func (m *CreateDORRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDORRequest) ProtoMessage()    {}
func (*CreateDORRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{27}
}
func (m *CreateDORRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDORRequest.Unmarshal(m, b)
}
func (m *CreateDORRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDORRequest.Marshal(b, m, deterministic)
}
func (dst *CreateDORRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDORRequest.Merge(dst, src)
}
func (m *CreateDORRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDORRequest.Size(m)
}
func (m *CreateDORRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDORRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDORRequest proto.InternalMessageInfo

func (m *CreateDORRequest) GetDor() *DOR {
	if m != nil {
		return m.Dor
	}
	return nil
}

type ReadDORResponse struct {
	Dor                  *DOR     `protobuf:"bytes,1,opt,name=dor,proto3" json:"dor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadDORResponse) Reset()         { *m = ReadDORResponse{} }
func (m *ReadDORResponse) String() string { return proto.CompactTextString(m) }
func (*ReadDORResponse) ProtoMessage()    {}
func (*ReadDORResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{28}
}
func (m *ReadDORResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadDORResponse.Unmarshal(m, b)
}
func (m *ReadDORResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadDORResponse.Marshal(b, m, deterministic)
}
func (dst *ReadDORResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadDORResponse.Merge(dst, src)
}
func (m *ReadDORResponse) XXX_Size() int {
	return xxx_messageInfo_ReadDORResponse.Size(m)
}
func (m *ReadDORResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadDORResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadDORResponse proto.InternalMessageInfo

func (m *ReadDORResponse) GetDor() *DOR {
	if m != nil {
		return m.Dor
	}
	return nil
}

type UpdateDORRequest struct {
	Dor                  *DOR     `protobuf:"bytes,1,opt,name=dor,proto3" json:"dor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDORRequest) Reset()         { *m = UpdateDORRequest{} }
func (m *UpdateDORRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateDORRequest) ProtoMessage()    {}
func (*UpdateDORRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{29}
}
func (m *UpdateDORRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDORRequest.Unmarshal(m, b)
}
func (m *UpdateDORRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDORRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateDORRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDORRequest.Merge(dst, src)
}
func (m *UpdateDORRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateDORRequest.Size(m)
}
func (m *UpdateDORRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDORRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDORRequest proto.InternalMessageInfo

func (m *UpdateDORRequest) GetDor() *DOR {
	if m != nil {
		return m.Dor
	}
	return nil
}

// HR
type CreateHRRequest struct {
	Hr                   *HR      `protobuf:"bytes,1,opt,name=hr,proto3" json:"hr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateHRRequest) Reset()         { *m = CreateHRRequest{} }
func (m *CreateHRRequest) String() string { return proto.CompactTextString(m) }
func (*CreateHRRequest) ProtoMessage()    {}
func (*CreateHRRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{30}
}
func (m *CreateHRRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHRRequest.Unmarshal(m, b)
}
func (m *CreateHRRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHRRequest.Marshal(b, m, deterministic)
}
func (dst *CreateHRRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHRRequest.Merge(dst, src)
}
func (m *CreateHRRequest) XXX_Size() int {
	return xxx_messageInfo_CreateHRRequest.Size(m)
}
func (m *CreateHRRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHRRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHRRequest proto.InternalMessageInfo

func (m *CreateHRRequest) GetHr() *HR {
	if m != nil {
		return m.Hr
	}
	return nil
}

type ReadHRResponse struct {
	Hr                   *HR      `protobuf:"bytes,1,opt,name=hr,proto3" json:"hr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadHRResponse) Reset()         { *m = ReadHRResponse{} }
func (m *ReadHRResponse) String() string { return proto.CompactTextString(m) }
func (*ReadHRResponse) ProtoMessage()    {}
func (*ReadHRResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{31}
}
func (m *ReadHRResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadHRResponse.Unmarshal(m, b)
}
func (m *ReadHRResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadHRResponse.Marshal(b, m, deterministic)
}
func (dst *ReadHRResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadHRResponse.Merge(dst, src)
}
func (m *ReadHRResponse) XXX_Size() int {
	return xxx_messageInfo_ReadHRResponse.Size(m)
}
func (m *ReadHRResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadHRResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadHRResponse proto.InternalMessageInfo

func (m *ReadHRResponse) GetHr() *HR {
	if m != nil {
		return m.Hr
	}
	return nil
}

type UpdateHRRequest struct {
	Hr                   *HR      `protobuf:"bytes,1,opt,name=hr,proto3" json:"hr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateHRRequest) Reset()         { *m = UpdateHRRequest{} }
func (m *UpdateHRRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateHRRequest) ProtoMessage()    {}
func (*UpdateHRRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{32}
}
func (m *UpdateHRRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateHRRequest.Unmarshal(m, b)
}
func (m *UpdateHRRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateHRRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateHRRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateHRRequest.Merge(dst, src)
}
func (m *UpdateHRRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateHRRequest.Size(m)
}
func (m *UpdateHRRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateHRRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateHRRequest proto.InternalMessageInfo

func (m *UpdateHRRequest) GetHr() *HR {
	if m != nil {
		return m.Hr
	}
	return nil
}

type GetAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllRequest) Reset()         { *m = GetAllRequest{} }
func (m *GetAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllRequest) ProtoMessage()    {}
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{33}
}
func (m *GetAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRequest.Unmarshal(m, b)
}
func (m *GetAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRequest.Marshal(b, m, deterministic)
}
func (dst *GetAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRequest.Merge(dst, src)
}
func (m *GetAllRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllRequest.Size(m)
}
func (m *GetAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRequest proto.InternalMessageInfo

type GetAllECResponse struct {
	Ecs                  []*EC    `protobuf:"bytes,1,rep,name=ecs,proto3" json:"ecs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllECResponse) Reset()         { *m = GetAllECResponse{} }
func (m *GetAllECResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllECResponse) ProtoMessage()    {}
func (*GetAllECResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_0c2878694a52fd87, []int{34}
}
func (m *GetAllECResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllECResponse.Unmarshal(m, b)
}
func (m *GetAllECResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllECResponse.Marshal(b, m, deterministic)
}
func (dst *GetAllECResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllECResponse.Merge(dst, src)
}
func (m *GetAllECResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllECResponse.Size(m)
}
func (m *GetAllECResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllECResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllECResponse proto.InternalMessageInfo

func (m *GetAllECResponse) GetEcs() []*EC {
	if m != nil {
		return m.Ecs
	}
	return nil
}

func init() {
	proto.RegisterType((*Student)(nil), "userproto.Student")
	proto.RegisterType((*Secretariat)(nil), "userproto.Secretariat")
	proto.RegisterType((*EC)(nil), "userproto.EC")
	proto.RegisterType((*DOR)(nil), "userproto.DOR")
	proto.RegisterType((*PI)(nil), "userproto.PI")
	proto.RegisterType((*CoI)(nil), "userproto.CoI")
	proto.RegisterType((*HR)(nil), "userproto.HR")
	proto.RegisterType((*CreateResponse)(nil), "userproto.CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "userproto.ReadRequest")
	proto.RegisterType((*UpdateResponse)(nil), "userproto.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "userproto.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "userproto.DeleteResponse")
	proto.RegisterType((*CreateStudentRequest)(nil), "userproto.CreateStudentRequest")
	proto.RegisterType((*ReadStudentResponse)(nil), "userproto.ReadStudentResponse")
	proto.RegisterType((*UpdateStudentRequest)(nil), "userproto.UpdateStudentRequest")
	proto.RegisterType((*CreateECRequest)(nil), "userproto.CreateECRequest")
	proto.RegisterType((*ReadECResponse)(nil), "userproto.ReadECResponse")
	proto.RegisterType((*UpdateECRequest)(nil), "userproto.UpdateECRequest")
	proto.RegisterType((*CreateSecretariatRequest)(nil), "userproto.CreateSecretariatRequest")
	proto.RegisterType((*ReadSecretariatResponse)(nil), "userproto.ReadSecretariatResponse")
	proto.RegisterType((*UpdateSecretariatRequest)(nil), "userproto.UpdateSecretariatRequest")
	proto.RegisterType((*CreatePIRequest)(nil), "userproto.CreatePIRequest")
	proto.RegisterType((*ReadPIResponse)(nil), "userproto.ReadPIResponse")
	proto.RegisterType((*UpdatePIRequest)(nil), "userproto.UpdatePIRequest")
	proto.RegisterType((*CreateCoIRequest)(nil), "userproto.CreateCoIRequest")
	proto.RegisterType((*ReadCoIResponse)(nil), "userproto.ReadCoIResponse")
	proto.RegisterType((*UpdateCoIRequest)(nil), "userproto.UpdateCoIRequest")
	proto.RegisterType((*CreateDORRequest)(nil), "userproto.CreateDORRequest")
	proto.RegisterType((*ReadDORResponse)(nil), "userproto.ReadDORResponse")
	proto.RegisterType((*UpdateDORRequest)(nil), "userproto.UpdateDORRequest")
	proto.RegisterType((*CreateHRRequest)(nil), "userproto.CreateHRRequest")
	proto.RegisterType((*ReadHRResponse)(nil), "userproto.ReadHRResponse")
	proto.RegisterType((*UpdateHRRequest)(nil), "userproto.UpdateHRRequest")
	proto.RegisterType((*GetAllRequest)(nil), "userproto.GetAllRequest")
	proto.RegisterType((*GetAllECResponse)(nil), "userproto.GetAllECResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateStudent(ctx context.Context, in *CreateStudentRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	ReadStudent(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadStudentResponse, error)
	UpdateStudent(ctx context.Context, in *UpdateStudentRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	DeleteStudent(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	CreatePI(ctx context.Context, in *CreatePIRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	ReadPI(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadPIResponse, error)
	UpdatePI(ctx context.Context, in *UpdatePIRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	DeletePI(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	CreateCoI(ctx context.Context, in *CreateCoIRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	ReadCoI(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadCoIResponse, error)
	UpdateCoI(ctx context.Context, in *UpdateCoIRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	DeleteCoI(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	CreateEC(ctx context.Context, in *CreateECRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	ReadEC(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadECResponse, error)
	UpdateEC(ctx context.Context, in *UpdateECRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	DeleteEC(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	GetAllEC(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllECResponse, error)
	CreateDOR(ctx context.Context, in *CreateDORRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	ReadDOR(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadDORResponse, error)
	UpdateDOR(ctx context.Context, in *UpdateDORRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	DeleteDOR(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	CreateSecretariat(ctx context.Context, in *CreateSecretariatRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	ReadSecretariat(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadSecretariatResponse, error)
	UpdateSecretariat(ctx context.Context, in *UpdateSecretariatRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	DeleteSecretariat(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	CreateHR(ctx context.Context, in *CreateHRRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	ReadHR(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadHRResponse, error)
	UpdateHR(ctx context.Context, in *UpdateHRRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	DeleteHR(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateStudent(ctx context.Context, in *CreateStudentRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/CreateStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ReadStudent(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadStudentResponse, error) {
	out := new(ReadStudentResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/ReadStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateStudent(ctx context.Context, in *UpdateStudentRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/UpdateStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteStudent(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/DeleteStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreatePI(ctx context.Context, in *CreatePIRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/CreatePI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ReadPI(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadPIResponse, error) {
	out := new(ReadPIResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/ReadPI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdatePI(ctx context.Context, in *UpdatePIRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/UpdatePI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeletePI(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/DeletePI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateCoI(ctx context.Context, in *CreateCoIRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/CreateCoI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ReadCoI(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadCoIResponse, error) {
	out := new(ReadCoIResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/ReadCoI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateCoI(ctx context.Context, in *UpdateCoIRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/UpdateCoI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteCoI(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/DeleteCoI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateEC(ctx context.Context, in *CreateECRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/CreateEC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ReadEC(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadECResponse, error) {
	out := new(ReadECResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/ReadEC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateEC(ctx context.Context, in *UpdateECRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/UpdateEC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteEC(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/DeleteEC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetAllEC(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllECResponse, error) {
	out := new(GetAllECResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/GetAllEC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateDOR(ctx context.Context, in *CreateDORRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/CreateDOR", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ReadDOR(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadDORResponse, error) {
	out := new(ReadDORResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/ReadDOR", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateDOR(ctx context.Context, in *UpdateDORRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/UpdateDOR", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteDOR(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/DeleteDOR", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateSecretariat(ctx context.Context, in *CreateSecretariatRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/CreateSecretariat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ReadSecretariat(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadSecretariatResponse, error) {
	out := new(ReadSecretariatResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/ReadSecretariat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateSecretariat(ctx context.Context, in *UpdateSecretariatRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/UpdateSecretariat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteSecretariat(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/DeleteSecretariat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateHR(ctx context.Context, in *CreateHRRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/CreateHR", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ReadHR(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadHRResponse, error) {
	out := new(ReadHRResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/ReadHR", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateHR(ctx context.Context, in *UpdateHRRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/UpdateHR", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteHR(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/userproto.UserService/DeleteHR", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateStudent(context.Context, *CreateStudentRequest) (*CreateResponse, error)
	ReadStudent(context.Context, *ReadRequest) (*ReadStudentResponse, error)
	UpdateStudent(context.Context, *UpdateStudentRequest) (*UpdateResponse, error)
	DeleteStudent(context.Context, *DeleteRequest) (*DeleteResponse, error)
	CreatePI(context.Context, *CreatePIRequest) (*CreateResponse, error)
	ReadPI(context.Context, *ReadRequest) (*ReadPIResponse, error)
	UpdatePI(context.Context, *UpdatePIRequest) (*UpdateResponse, error)
	DeletePI(context.Context, *DeleteRequest) (*DeleteResponse, error)
	CreateCoI(context.Context, *CreateCoIRequest) (*CreateResponse, error)
	ReadCoI(context.Context, *ReadRequest) (*ReadCoIResponse, error)
	UpdateCoI(context.Context, *UpdateCoIRequest) (*UpdateResponse, error)
	DeleteCoI(context.Context, *DeleteRequest) (*DeleteResponse, error)
	CreateEC(context.Context, *CreateECRequest) (*CreateResponse, error)
	ReadEC(context.Context, *ReadRequest) (*ReadECResponse, error)
	UpdateEC(context.Context, *UpdateECRequest) (*UpdateResponse, error)
	DeleteEC(context.Context, *DeleteRequest) (*DeleteResponse, error)
	GetAllEC(context.Context, *GetAllRequest) (*GetAllECResponse, error)
	CreateDOR(context.Context, *CreateDORRequest) (*CreateResponse, error)
	ReadDOR(context.Context, *ReadRequest) (*ReadDORResponse, error)
	UpdateDOR(context.Context, *UpdateDORRequest) (*UpdateResponse, error)
	DeleteDOR(context.Context, *DeleteRequest) (*DeleteResponse, error)
	CreateSecretariat(context.Context, *CreateSecretariatRequest) (*CreateResponse, error)
	ReadSecretariat(context.Context, *ReadRequest) (*ReadSecretariatResponse, error)
	UpdateSecretariat(context.Context, *UpdateSecretariatRequest) (*UpdateResponse, error)
	DeleteSecretariat(context.Context, *DeleteRequest) (*DeleteResponse, error)
	CreateHR(context.Context, *CreateHRRequest) (*CreateResponse, error)
	ReadHR(context.Context, *ReadRequest) (*ReadHRResponse, error)
	UpdateHR(context.Context, *UpdateHRRequest) (*UpdateResponse, error)
	DeleteHR(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/CreateStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateStudent(ctx, req.(*CreateStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ReadStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ReadStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/ReadStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ReadStudent(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/UpdateStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateStudent(ctx, req.(*UpdateStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/DeleteStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteStudent(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreatePI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreatePI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/CreatePI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreatePI(ctx, req.(*CreatePIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ReadPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ReadPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/ReadPI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ReadPI(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdatePI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdatePI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/UpdatePI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdatePI(ctx, req.(*UpdatePIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeletePI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeletePI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/DeletePI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeletePI(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateCoI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCoIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateCoI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/CreateCoI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateCoI(ctx, req.(*CreateCoIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ReadCoI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ReadCoI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/ReadCoI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ReadCoI(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateCoI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCoIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateCoI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/UpdateCoI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateCoI(ctx, req.(*UpdateCoIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteCoI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteCoI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/DeleteCoI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteCoI(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateEC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateECRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateEC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/CreateEC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateEC(ctx, req.(*CreateECRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ReadEC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ReadEC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/ReadEC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ReadEC(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateEC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateECRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateEC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/UpdateEC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateEC(ctx, req.(*UpdateECRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteEC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteEC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/DeleteEC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteEC(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetAllEC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetAllEC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/GetAllEC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetAllEC(ctx, req.(*GetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateDOR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDORRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateDOR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/CreateDOR",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateDOR(ctx, req.(*CreateDORRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ReadDOR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ReadDOR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/ReadDOR",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ReadDOR(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateDOR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDORRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateDOR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/UpdateDOR",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateDOR(ctx, req.(*UpdateDORRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteDOR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteDOR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/DeleteDOR",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteDOR(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateSecretariat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSecretariatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateSecretariat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/CreateSecretariat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateSecretariat(ctx, req.(*CreateSecretariatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ReadSecretariat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ReadSecretariat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/ReadSecretariat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ReadSecretariat(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateSecretariat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSecretariatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateSecretariat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/UpdateSecretariat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateSecretariat(ctx, req.(*UpdateSecretariatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteSecretariat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteSecretariat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/DeleteSecretariat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteSecretariat(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateHR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateHR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/CreateHR",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateHR(ctx, req.(*CreateHRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ReadHR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ReadHR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/ReadHR",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ReadHR(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateHR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateHR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/UpdateHR",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateHR(ctx, req.(*UpdateHRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteHR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteHR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userproto.UserService/DeleteHR",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteHR(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "userproto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStudent",
			Handler:    _UserService_CreateStudent_Handler,
		},
		{
			MethodName: "ReadStudent",
			Handler:    _UserService_ReadStudent_Handler,
		},
		{
			MethodName: "UpdateStudent",
			Handler:    _UserService_UpdateStudent_Handler,
		},
		{
			MethodName: "DeleteStudent",
			Handler:    _UserService_DeleteStudent_Handler,
		},
		{
			MethodName: "CreatePI",
			Handler:    _UserService_CreatePI_Handler,
		},
		{
			MethodName: "ReadPI",
			Handler:    _UserService_ReadPI_Handler,
		},
		{
			MethodName: "UpdatePI",
			Handler:    _UserService_UpdatePI_Handler,
		},
		{
			MethodName: "DeletePI",
			Handler:    _UserService_DeletePI_Handler,
		},
		{
			MethodName: "CreateCoI",
			Handler:    _UserService_CreateCoI_Handler,
		},
		{
			MethodName: "ReadCoI",
			Handler:    _UserService_ReadCoI_Handler,
		},
		{
			MethodName: "UpdateCoI",
			Handler:    _UserService_UpdateCoI_Handler,
		},
		{
			MethodName: "DeleteCoI",
			Handler:    _UserService_DeleteCoI_Handler,
		},
		{
			MethodName: "CreateEC",
			Handler:    _UserService_CreateEC_Handler,
		},
		{
			MethodName: "ReadEC",
			Handler:    _UserService_ReadEC_Handler,
		},
		{
			MethodName: "UpdateEC",
			Handler:    _UserService_UpdateEC_Handler,
		},
		{
			MethodName: "DeleteEC",
			Handler:    _UserService_DeleteEC_Handler,
		},
		{
			MethodName: "GetAllEC",
			Handler:    _UserService_GetAllEC_Handler,
		},
		{
			MethodName: "CreateDOR",
			Handler:    _UserService_CreateDOR_Handler,
		},
		{
			MethodName: "ReadDOR",
			Handler:    _UserService_ReadDOR_Handler,
		},
		{
			MethodName: "UpdateDOR",
			Handler:    _UserService_UpdateDOR_Handler,
		},
		{
			MethodName: "DeleteDOR",
			Handler:    _UserService_DeleteDOR_Handler,
		},
		{
			MethodName: "CreateSecretariat",
			Handler:    _UserService_CreateSecretariat_Handler,
		},
		{
			MethodName: "ReadSecretariat",
			Handler:    _UserService_ReadSecretariat_Handler,
		},
		{
			MethodName: "UpdateSecretariat",
			Handler:    _UserService_UpdateSecretariat_Handler,
		},
		{
			MethodName: "DeleteSecretariat",
			Handler:    _UserService_DeleteSecretariat_Handler,
		},
		{
			MethodName: "CreateHR",
			Handler:    _UserService_CreateHR_Handler,
		},
		{
			MethodName: "ReadHR",
			Handler:    _UserService_ReadHR_Handler,
		},
		{
			MethodName: "UpdateHR",
			Handler:    _UserService_UpdateHR_Handler,
		},
		{
			MethodName: "DeleteHR",
			Handler:    _UserService_DeleteHR_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_0c2878694a52fd87) }

var fileDescriptor_user_0c2878694a52fd87 = []byte{
	// 1039 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0xb6, 0xc8, 0x44, 0xb2, 0x46, 0x90, 0xad, 0x6c, 0x8c, 0x94, 0x51, 0x9a, 0xda, 0x60, 0x73,
	0xc8, 0xa1, 0x70, 0x8c, 0xb8, 0x40, 0x4f, 0x6d, 0x91, 0x50, 0x6a, 0xe8, 0x02, 0xad, 0x8c, 0x35,
	0x7c, 0xe9, 0x8d, 0x21, 0x47, 0x36, 0x0b, 0x99, 0x54, 0x48, 0xaa, 0x68, 0xfb, 0x20, 0x3d, 0xb5,
	0xaf, 0xd0, 0xf7, 0xe9, 0xdb, 0x14, 0xfb, 0xc3, 0xe5, 0xf2, 0x47, 0x0a, 0x65, 0x1d, 0xda, 0x93,
	0xc8, 0xd9, 0xf9, 0x86, 0xdf, 0x7e, 0x3b, 0xfb, 0xed, 0x42, 0x00, 0xab, 0x14, 0x93, 0xd3, 0x65,
	0x12, 0x67, 0x31, 0xe9, 0xb3, 0x67, 0xfe, 0x68, 0xff, 0xd3, 0x81, 0xde, 0x55, 0xb6, 0x0a, 0x30,
	0xca, 0xc8, 0x11, 0x3c, 0xc4, 0x3b, 0x2f, 0x5c, 0x58, 0x9d, 0x93, 0xce, 0xcb, 0x3e, 0x15, 0x2f,
	0x84, 0xc0, 0x83, 0xc8, 0xbb, 0x43, 0xcb, 0xe0, 0x41, 0xfe, 0x4c, 0x2c, 0xe8, 0x79, 0x41, 0x90,
	0x60, 0x9a, 0x5a, 0x26, 0x0f, 0xe7, 0xaf, 0xe4, 0x04, 0x06, 0xcb, 0xdb, 0x38, 0xc2, 0x1f, 0x57,
	0x77, 0xef, 0x31, 0xb1, 0x1e, 0xf0, 0x51, 0x3d, 0x44, 0x9e, 0x40, 0xf7, 0x06, 0xa3, 0x00, 0x13,
	0xeb, 0x21, 0x1f, 0x94, 0x6f, 0xe4, 0x05, 0x0c, 0xb3, 0xdf, 0x96, 0x38, 0x9b, 0x4b, 0x3a, 0x56,
	0x97, 0x0f, 0x97, 0x83, 0x64, 0x04, 0x66, 0x10, 0xff, 0x6c, 0xf5, 0xf8, 0x18, 0x7b, 0x64, 0x5c,
	0xfc, 0x04, 0xbd, 0x0c, 0x03, 0x6b, 0x5f, 0x70, 0x91, 0xaf, 0xf6, 0x57, 0x30, 0xb8, 0x42, 0x3f,
	0xc1, 0xcc, 0x4b, 0x42, 0x6f, 0x8b, 0xe9, 0xd9, 0x7f, 0x1b, 0x60, 0x4c, 0x9d, 0x2d, 0xf4, 0x78,
	0x01, 0xc3, 0x0f, 0x2b, 0x6f, 0x11, 0xce, 0x43, 0xdf, 0xcb, 0xc2, 0x38, 0x92, 0xaa, 0x94, 0x83,
	0xe4, 0x0c, 0x1e, 0xfb, 0xab, 0x24, 0xc1, 0x28, 0x9b, 0x25, 0x37, 0x5e, 0x14, 0xfe, 0x2e, 0x72,
	0x85, 0x46, 0x4d, 0x43, 0xe4, 0x53, 0xe8, 0x67, 0xb8, 0x40, 0x2e, 0x9f, 0x94, 0xab, 0x08, 0x30,
	0x2d, 0xe6, 0xde, 0xaf, 0x52, 0x27, 0xf6, 0xc8, 0xd4, 0x0f, 0x30, 0x0d, 0x6f, 0x22, 0x51, 0x59,
	0xa8, 0xa4, 0x87, 0x58, 0x86, 0x37, 0x9f, 0x87, 0x8b, 0x50, 0x64, 0x08, 0xc5, 0xf4, 0x90, 0xb6,
	0x3e, 0xfd, 0xd2, 0xfa, 0x8c, 0x61, 0x7f, 0x19, 0xa7, 0x21, 0x87, 0x01, 0x1f, 0x51, 0xef, 0xf6,
	0x2b, 0x30, 0x27, 0x33, 0xba, 0x85, 0xc2, 0x7f, 0x76, 0xc0, 0xb8, 0xbc, 0xf8, 0x8f, 0x3b, 0x4e,
	0xeb, 0x9c, 0x6e, 0xb9, 0x73, 0xfe, 0xea, 0x80, 0xe9, 0xc4, 0xff, 0x5f, 0x7e, 0xdf, 0x80, 0xe1,
	0x52, 0x72, 0x00, 0x46, 0x18, 0x48, 0x6a, 0x46, 0x18, 0x34, 0xf2, 0x52, 0x33, 0x30, 0xb5, 0x19,
	0xd8, 0x23, 0x38, 0x70, 0x78, 0x29, 0x8a, 0xe9, 0x32, 0x8e, 0x52, 0xb4, 0x9f, 0xc3, 0x80, 0xa2,
	0x17, 0x50, 0xfc, 0xb0, 0xc2, 0x34, 0xab, 0x96, 0x66, 0x80, 0xeb, 0x65, 0xa0, 0x03, 0x8e, 0x61,
	0x38, 0xc1, 0x05, 0xb2, 0xc8, 0x5a, 0x48, 0x9e, 0x20, 0x21, 0x13, 0x38, 0x12, 0x5f, 0x95, 0x9b,
	0x39, 0x47, 0x7e, 0x01, 0xbd, 0x54, 0xee, 0x79, 0x06, 0x1f, 0xbc, 0x26, 0xa7, 0xca, 0xa0, 0x4e,
	0xf3, 0xdc, 0x3c, 0xc5, 0x76, 0xe0, 0x31, 0x63, 0xaa, 0x6a, 0x88, 0xe2, 0x5b, 0x16, 0x99, 0xc0,
	0x91, 0x98, 0xcf, 0x4e, 0x54, 0xce, 0xe0, 0x50, 0x4c, 0x68, 0xea, 0xe4, 0x05, 0x9e, 0x83, 0x81,
	0xbe, 0xc4, 0x0e, 0x35, 0xec, 0xd4, 0xa1, 0x06, 0xfa, 0xf6, 0x2b, 0x38, 0x60, 0xe4, 0x59, 0xbe,
	0xe4, 0xfd, 0x11, 0xc0, 0x19, 0x1c, 0x0a, 0xa2, 0xad, 0x3f, 0x31, 0x01, 0x4b, 0xaa, 0x5c, 0x78,
	0x5f, 0x0e, 0x7d, 0x09, 0x66, 0xaa, 0xb0, 0x4f, 0xf4, 0xa9, 0x69, 0xb9, 0x2c, 0xc5, 0x76, 0xe0,
	0x13, 0xae, 0xb2, 0x5e, 0x43, 0x32, 0x6e, 0x5f, 0x64, 0x02, 0x96, 0x54, 0x79, 0x17, 0x2a, 0x4a,
	0xe5, 0xcb, 0x0b, 0x4d, 0x82, 0x65, 0xd8, 0x20, 0xc1, 0xe5, 0x05, 0x35, 0x96, 0x61, 0xae, 0x32,
	0xcb, 0x2f, 0x54, 0xde, 0x04, 0x50, 0x2a, 0xb7, 0xfe, 0xc4, 0x39, 0x8c, 0x04, 0x29, 0x27, 0x56,
	0x90, 0x63, 0x30, 0xfd, 0x38, 0x6c, 0x5e, 0x19, 0x36, 0x62, 0x9f, 0xc3, 0x21, 0xe3, 0xc5, 0x21,
	0x92, 0xd8, 0x89, 0x8e, 0x39, 0xd0, 0x30, 0x2c, 0x89, 0x83, 0xbe, 0x84, 0x91, 0xe0, 0xa6, 0x7d,
	0xa9, 0x15, 0x4a, 0xf0, 0x9b, 0xcc, 0xa8, 0x86, 0x0a, 0xe2, 0xa4, 0x01, 0xc5, 0x72, 0xd8, 0x50,
	0x4e, 0x90, 0x63, 0x0a, 0x82, 0x1f, 0x01, 0x29, 0x82, 0x5b, 0x7d, 0x4a, 0xad, 0xaa, 0x4b, 0x35,
	0xc9, 0x6f, 0x93, 0x06, 0xf9, 0x5c, 0x4a, 0x8d, 0xdb, 0x24, 0x5f, 0x55, 0x97, 0xea, 0xab, 0xba,
	0x09, 0xa0, 0x56, 0xb5, 0xf5, 0x27, 0x0e, 0x61, 0xf8, 0x0e, 0xb3, 0x37, 0x8b, 0x85, 0xcc, 0x67,
	0xcb, 0x2c, 0x02, 0xda, 0x8e, 0x3d, 0x06, 0x13, 0xfd, 0xd4, 0xea, 0x9c, 0x98, 0x0d, 0xcb, 0x8c,
	0x7e, 0xfa, 0xfa, 0x8f, 0x11, 0x0c, 0xae, 0x53, 0x4c, 0xae, 0x30, 0xf9, 0x25, 0xf4, 0x91, 0xfc,
	0x00, 0xc3, 0x92, 0xef, 0x91, 0x63, 0x7d, 0xc5, 0x1a, 0x1c, 0x71, 0xfc, 0xb4, 0x96, 0xa0, 0x4c,
	0x74, 0x8f, 0xbc, 0x13, 0x56, 0x9d, 0x17, 0xd3, 0xf7, 0x8e, 0x66, 0xe1, 0xe3, 0xcf, 0x2a, 0xf1,
	0x8a, 0x61, 0xda, 0x7b, 0x8c, 0x57, 0xc9, 0x04, 0x4b, 0xbc, 0x9a, 0xec, 0xb1, 0xc4, 0xab, 0x72,
	0x1e, 0xec, 0x91, 0xef, 0xf2, 0x13, 0x21, 0x2f, 0x67, 0xe9, 0xeb, 0xae, 0x9f, 0x15, 0xa5, 0x3a,
	0x95, 0x43, 0x62, 0x8f, 0x38, 0xb0, 0x9f, 0xef, 0x77, 0x32, 0xae, 0x09, 0xa1, 0x76, 0xe8, 0x66,
	0x91, 0xbe, 0x86, 0xae, 0xb0, 0x80, 0xb5, 0xfa, 0x3c, 0xad, 0xc4, 0x0b, 0xb7, 0x10, 0x1c, 0x72,
	0x43, 0x28, 0x71, 0xa8, 0xb8, 0xc4, 0x66, 0x41, 0xde, 0xc0, 0xbe, 0x98, 0xdc, 0xe5, 0xc5, 0x7d,
	0xb5, 0x98, 0x42, 0x5f, 0xd9, 0x0c, 0x79, 0x56, 0x9b, 0x70, 0x61, 0x09, 0x9b, 0xd5, 0xf8, 0x16,
	0x7a, 0xd2, 0x78, 0xd6, 0xca, 0x31, 0xae, 0xc4, 0x35, 0x93, 0x12, 0x3c, 0x94, 0x09, 0x95, 0x78,
	0x54, 0xad, 0x69, 0xb3, 0x22, 0x6f, 0xa1, 0x2f, 0xa6, 0xc8, 0xca, 0xec, 0xda, 0x1e, 0x53, 0xa7,
	0xa1, 0x3d, 0xd4, 0x31, 0xd9, 0xaa, 0x3d, 0xa6, 0x4e, 0xeb, 0xf6, 0x28, 0x0c, 0x40, 0x6f, 0x8f,
	0x0a, 0x87, 0xca, 0x51, 0xdd, 0xb2, 0x3d, 0xa6, 0xce, 0x0e, 0x5a, 0xe4, 0xf6, 0x54, 0x2a, 0x51,
	0x32, 0xb1, 0xf1, 0xb3, 0xda, 0x48, 0x69, 0x32, 0xaa, 0xc7, 0xd8, 0x15, 0xbe, 0xde, 0x63, 0x85,
	0xab, 0xb7, 0xea, 0x31, 0x56, 0xa4, 0x6d, 0x8f, 0x69, 0xe7, 0x8c, 0xde, 0x63, 0x55, 0x1e, 0xd5,
	0xd3, 0xa5, 0x65, 0x8f, 0xb1, 0x32, 0xf7, 0xd4, 0xf5, 0x1a, 0x1e, 0xd5, 0xee, 0x50, 0xe4, 0xf3,
	0xba, 0x6b, 0xd7, 0xae, 0x35, 0x9b, 0x25, 0x9a, 0x89, 0xe3, 0x55, 0x2f, 0xba, 0x4e, 0x2a, 0xbb,
	0xea, 0xde, 0xf5, 0x8b, 0x98, 0xe0, 0x59, 0xbb, 0x60, 0x95, 0x78, 0xae, 0xbb, 0x7e, 0x6d, 0x96,
	0xf0, 0x7b, 0x78, 0x24, 0x9d, 0x5c, 0x2b, 0xbb, 0xeb, 0x76, 0x75, 0x69, 0xc3, 0x76, 0x75, 0xe9,
	0x36, 0xdb, 0xd5, 0xa5, 0xad, 0xb7, 0xab, 0x4b, 0x9b, 0xb6, 0x6b, 0x85, 0x43, 0xe5, 0x76, 0xd0,
	0x72, 0xbb, 0xba, 0xf7, 0x6d, 0xab, 0xb7, 0x83, 0x9f, 0x8a, 0x7f, 0x5e, 0xde, 0x77, 0xf9, 0xcf,
	0xf9, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x94, 0x0c, 0xa5, 0x99, 0x11, 0x00, 0x00,
}
