version = "unstable"
plugins = ["grpc"]

# [packages]
#   "gogoproto/gogo.proto" = "github.com/gogo/protobuf/gogoproto"
#   "google/protobuf/any.proto" = "github.com/google/protobuf/types"
#   "google/protobuf/descriptor.proto" = "github.com/google/protobuf/protoc-gen-gogo/descriptor"
#   "google/protobuf/field_mask.proto" = "github.com/google/protobuf/types"
#   "google/protobuf/timestamp.proto" = "github.com/google/protobuf/types"
#   "google/protobuf/duration.proto" = "github.com/google/protobuf/types"
#   "google/protobuf/wrappers.proto" = "github.com/google/protobuf/types"

[[descriptors]]
prefix = "chappie-smarthome/chappie-cloud/auth-srv/proto"
target = "proto/descriptors.pb.txt"